# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'seminar_4_practise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for seminar_4_practise
  pod 'Alamofire', '~> 5.2'

end
